apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Skip applying the Tekton/PaC operands while the Tekton/PaC operator is being installed.
# See more information about this option, here: 
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types 
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - https://github.com/openshift-pipelines/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service?ref=9bfc5b35d3c6a1b681f7a4ce30e89da06e586a2b
  - https://github.com/openshift-pipelines/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service-storage?ref=9bfc5b35d3c6a1b681f7a4ce30e89da06e586a2b
  - ../base/rbac
  
patches:
#  - path: scale-down-exporter.yaml
#    target:
#      kind: Deployment
#      name: pipeline-metrics-exporter
#      namespace: openshift-pipelines
  - path: update-tekton-config-performance.yaml
    target:
      kind: TektonConfig
      name: config
