apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=6c05ce9da27b6d4a5622f6f883d2ac266e93ad94
- overlays

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 6c05ce9da27b6d4a5622f6f883d2ac266e93ad94
