apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rhtap-staging-e2e
spec:
  params:
    - name: repo_url
    - name: revision
    - name: pull_request_number
    - name: source_branch
  workspaces:
    - name: git
    - name: shared-file
  tasks:
    - name: check-merge-label
      taskRef:
        name: pr-labels
      params:
        - name: pull_request_number
          value: $(params.pull_request_number)
        - name: match_label
          value: "ok-to-merge"
    - name: clone-infra-deployment-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.revision)
        - name: depth
          value: "3"
      runAfter:
        - check-merge-label
      when:
        - input: $(tasks.check-merge-label.results.matched-label)
          operator: in
          values: ["true"]
      workspaces:
      - name: output
        workspace: git
        subPath: infra-deployment-git
      timeout: 10m
    - name: get-pr-modified-files
      taskRef:
        name: get-pr-modified-files
      params:
        - name: revision
          value: $(params.revision)
      runAfter:
        - clone-infra-deployment-git
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
        - name: shared-file-path
          workspace: shared-file
    - name: changed-component-app-name
      taskRef:
        name: component-app-name
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
        - name: shared-file-path
          workspace: shared-file
      runAfter:
        - get-pr-modified-files
    - name: check-rebase-label
      taskRef:
        name: pr-labels
      params:
        - name: pull_request_number
          value: $(params.pull_request_number)
        - name: match_label
          value: "needs-rebase"
      runAfter:
        - get-pr-modified-files
    - name: rebase-pr
      taskRef:
        name: rebase-pr
      params:
        - name: pull_request_number
          value: $(params.pull_request_number)
        - name: source_branch
          value: $(params.source_branch)
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
      when:
        - input: $(tasks.check-rebase-label.results.matched-label)
          operator: in
          values: ["true"]
      runAfter:
        - check-rebase-label
    - name: replace-revision
      taskRef:
        name: replace-revision
      params:
        - name: pr_branch_revision
          value: $(tasks.rebase-pr.results.source-current-revision)
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
        - name: shared-file-path
          workspace: shared-file
      when:
        - input: $(tasks.check-rebase-label.results.matched-label)
          operator: in
          values: ["false"]
      runAfter:
        - changed-component-app-name
        - check-rebase-label
    - name: clone-stage-e2e-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: 'https://github.com/sawood14012/e2e-tests.git'
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "verify-stage"
      runAfter:
        - check-merge-label
      when:
        - input: $(tasks.check-merge-label.results.matched-label)
          operator: in
          values: ["true"]
      workspaces:
      - name: output
        workspace: git
        subPath: stage-e2e-git
      timeout: 10m
    - name: stage-verify-e2e-test
      taskRef:
        name: stage-verify-e2e-test
      params:
      - name: TASK_RETRIES
        value: "$(context.pipelineTask.retries)"
      workspaces:
      - name: stage-e2e-git
        workspace: git
        subPath: stage-e2e-git
      runAfter:
        - replace-revision
        - clone-stage-e2e-git
    - name: check-rebase-label-2
      taskRef:
        name: pr-labels
      params:
        - name: pull_request_number
          value: $(params.pull_request_number)
        - name: match_label
          value: "needs-rebase"
      runAfter:
        - stage-verify-e2e-test
    - name: remove-merge-label
      taskRef:
        name: remove-pr-labels
      params:
        - name: match_label
          value: "ok-to-merge"
        - name: pull_request_number
          value: $(params.pull_request_number)
      when:
        - input: $(tasks.check-merge-label-2.results.matched-label)
          operator: in
          values: ["true"]
      runAfter:
        - check-rebase-label-2
    - name: rebase-pr-3
      taskRef:
        name: rebase-pr
      params:
        - name: pull_request_number
          value: $(params.pull_request_number)
        - name: source_branch
          value: $(params.source_branch)
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
      runAfter:
        - remove-merge-label
  finally:
    - name: revert-replace-revision
      taskRef:
        name: revert-replace-revision
    - name: merge-pr
      taskRef:
        name: merge-pr
      params:
        - name: pull_request_number
          value: $(params.pull_request_number)
        - name: source_branch
          value: $(params.source_branch)
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
      when:
        - input: $(tasks.stage-verify-e2e-test.status)
          operator: in
          values: ["Succeeded"]
