apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: staging-hac-e2e-test
spec:
  params:
    - name: repo_url
    - name: revision
    - name: pull_request_title
    - name: SEND_SLACK_NOTIFICATION
      description: sends failed message to slack if the param is set to True/true
      default: "false"
  workspaces:
    - name: git
    - name: shared-workspace
  tasks:
    - name: staging-argocd-login
      taskRef:
        name: login-argocd
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: clone-infra-deployment-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "POCPromotionToProd"
      workspaces:
      - name: output
        workspace: git
        subPath: infra-deployment-git
      timeout: 10m
    - name: staging-argocd-app-sync
      taskRef:
        name: app-sync
      params:
        - name: pull_request_title
          value: $(params.pull_request_title)
        # - name: argocd_config
        #   value: $(tasks.staging-argocd-login.results.argocd-config)
      workspaces:
        - name: argocd-config
          workspace: shared-workspace
      runAfter:
        - staging-argocd-login
    - name: argocd-app-synced-healthy
      taskRef:
        name: argocd-app-health-check
      # params:
      #   - name: argocd_config
      #     value: $(tasks.staging-argocd-login.results.argocd-config)
      workspaces:
        - name: argocd-config
          workspace: shared-workspace
      runAfter:
        - staging-argocd-app-sync
    - name: clone-hac-ui-e2e-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: 'https://github.com/openshift/hac-dev.git'
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "main"
      workspaces:
      - name: output
        workspace: git
        subPath: hac-ui-e2e-git
      timeout: 10m
    - name: hac-ui-e2e-test
      taskRef:
        name: hac-ui-e2e-test
      params:
      - name: TASK_RETRIES
        value: "$(context.pipelineTask.retries)"
      workspaces:
      - name: hac-ui-e2e-git
        workspace: git
        subPath: hac-ui-e2e-git
      runAfter:
        - argocd-app-synced-healthy
        - clone-hac-ui-e2e-git
  finally:
    - name: send-slack-notification
      taskRef:
        name: send-slack-notification
      params:
        - name: MESSAGE
          value: |
            <icon> Staging e2e pipeline run <pr_name> *<run_status>* <icon> <<logs_url>|logs> <tag_ic>
      when:
        - input: $(tasks.hac-ui-e2e-test.status)
          operator: in
          values: ["Failed"]
        - input: $(params.SEND_SLACK_NOTIFICATION)
          operator: in
          values: ["true"]
