apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: component-app-name
spec:
  params:
   - name: APP_FILE_NAME
     description: This is the file which contains the argocd application names running as per the component.
     default: "staging-app.yaml"
  description: >-
    This task is for syncing the staging cluster argocd application
  workspaces:
   - name: infra-deployment-git
   - name: shared-file-path
  steps:
    - name: get-component-app-name
      image: quay.io/openshift-pipeline/ci
      workingDir: $(workspaces.infra-deployment-git.path)
      env:
        - name: APP_FILE_NAME
          value: $(params.APP_FILE_NAME)
      script: |
        #!/usr/bin/env python3
        import subprocess
        import re
        import os

        cmd = "pip3 install pyyaml"
        output = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stdout, stderr = output.communicate()

        app-file-name = os.environ.get('APP_FILE_NAME')

        # Get the current working directory
        current_dir = os.getcwd()

        # Load applications file
        with open(f'{current_dir}/{app-file-name}') as f:
          import yaml
          applications = yaml.safe_load(f)

        keys_pattern = r"\b(" + "|".join(re.escape(key) for key in applications.keys()) + r")\b"

        # Print the list of file paths
        apps = []
        for file in open("$(workspaces.shared-file-path.path)/updated_files.txt").readlines():
          file = file.strip()
          path_matches = re.findall(keys_pattern, file)
          apps.extend(path_matches)

        # Find app match in pull request files
        unique_apps = set(apps)

        def update_app_path(app_path, app_name):
          with open(app_path, "a") as f:
            f.write(app_name + "\n")

        if not unique_apps:
            print(f'No matching components found in pull request files. Add them to the {app-file-name} file.')
        else:
            for app in unique_apps:
                for app_name in applications.get(app, []):
                  update_app_path("$(workspaces.shared-file-path.path)/component.txt", app + ":" + app_name)
