apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: component-app-name
spec:
  params:
   - name: APP_FILE_NAME
     description: This is the file which contains the argocd applicationset names running as per the component.
     default: "staging-app.yaml"
  description: >-
    This task is to find out which applicationset needs to be updated for the staging cluster argocd application
  workspaces:
   - name: infra-deployment-git
   - name: shared-file-path
  steps:
    - name: get-component-app-name
      image: image-registry.openshift-image-registry.svc:5000/openshift/python:3.8
      workingDir: $(workspaces.infra-deployment-git.path)
      env:
        - name: APP_FILE_NAME
          value: $(params.APP_FILE_NAME)
      script: |
        #!/usr/bin/env bash
        set -eufx

        default_appset_file="$(pwd)/${APP_FILE_NAME}"

        python .tekton/hack/get-component-name.py --filepath ${default_appset_file} --app-fiepath "$(workspaces.shared-file-path.path)/component.txt" --pr-filepath "$(workspaces.shared-file-path.path)/updated_files.txt"