apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: replace-revision
spec:
  description: |
    replace the target revision to changed application in the pull request for rhtap stage testing.
  params:
    - name: pr_branch_revision
  workspaces:
   - name: shared-file-path
   - name: infra-deployment-git
  steps:
    - name: replace-target-revision
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: $(workspaces.infra-deployment-git.path)
      command:
        - /bin/bash
        - -c
        - ".tekton/hack/update-argocd-app-revision.sh --branch $(params.pr_branch_revision) --filepath $(workspaces.shared-file-path.path)/component.txt"
