apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: revert-replace-revision
spec:
  description: |
    revert the target revision to changed application in the pull request for rhtap stage testing.
  steps:
    - name: revert-revision
      image: quay.io/openshift-pipeline/ci
      script: |
        #!/usr/bin/env sh
        set -o errexit
        set -o nounset
        set -o pipefail

        echo "Enable auto sync for all-application-sets"
        oc patch applications.argoproj.io/all-application-sets -n openshift-gitops --type merge -p '{"spec":{"syncPolicy": {"automated":{"prune":true, "selfHeal":true}}}}'

        