apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: app-sync
spec:
  description: >-
    This task is for syncing the staging cluster argocd application
  params:
    - name: pull_request_title
      type: string
      description: Title of the pull request which has been merged to be deployed on RHTAP staging environment
      default: ""
    - name: argocd_config
  results:
    - name: app-name
      description: Name of the app to be synced
  steps:
    - name: argocd-app-sync
      image: quay.io/devtools_gitops/test_image:4.0.5
      env:
        - name: ARGOCD_CONFIG
          value: $(params.argocd_config)
      script: |
        #!/usr/bin/env sh
        set -u -o pipefail

        for i in $(argocd app list --config "${ARGOCD_CONFIG}"); do
          app_name = $(echo $(params.pull_request_title) | grep -o "\b$i\b")
          if [ -n $app_name ]; then
            echo "trigger the deployment"
            argocd app sync $app_name --config "${ARGOCD_CONFIG}"
            echo $app_name | tee $(results.app-name.path)
            break
          fi
        done

        if [ -z $app_name ]; then
          echo "app not found in the argocd"
        fi
