apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/openshift-pipelines/pipeline-service.git/operator/gitops/argocd/pipeline-service?ref=feee26ee2853088712f9e63357079c986a698077

patches:
  - path: update-tekton-config-performance.yaml
    target:
      kind: TektonConfig
      name: config
