apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../base/external-secrets

# patches:
#  - path: scale-down-exporter.yaml
#    target:
#      kind: Deployment
#      name: pipeline-metrics-exporter
#      namespace: openshift-pipelines
#hello
#test
