apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appstudio-gitops-service-argocd-argocd-application-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appstudio-gitops-service-argocd-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  namespace: rhtap-promotion-staging
