apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: staging-hac-e2e-
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "preview-POCPromotionToProd" &&
      (
        "**/staging/**".pathChanged() ||
        "argo-cd-apps/app-of-app-sets/base/**".pathChanged() ||
        "components/?/base/*".pathChanged()
      )
    pipelinesascode.tekton.dev/pipeline: "[.tekton/pipeline/staging-hac-ui-e2e.yaml]"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/login-argocd.yaml]"
    pipelinesascode.tekton.dev/task-1: "[.tekton/tasks/sync-argocd-app.yaml]"
    pipelinesascode.tekton.dev/task-2: "[.tekton/tasks/stage-verify-e2e.yaml]"
    pipelinesascode.tekton.dev/task-3: "[.tekton/tasks/check-app-health.yaml]"
    pipelinesascode.tekton.dev/task-4: "[.tekton/tasks/send-slack-notification.yaml]"
    pipelinesascode.tekton.dev/task-5: "[.tekton/tasks/get-pr-commit-message.yaml]"
    pipelinesascode.tekton.dev/task-6: "[.tekton/tasks/rollback-argocd-app.yaml]"
    pipelinesascode.tekton.dev/task-7: "[.tekton/tasks/get-pr-number.yaml]"
    pipelinesascode.tekton.dev/task-8: "[.tekton/tasks/test-channel.yaml]"
    pipelinesascode.tekton.dev/task-9: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: SEND_SLACK_NOTIFICATION
      value: "false"
  pipelineRef:
    name: staging-hac-e2e-test
  workspaces:
    - name: git
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
