resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/integration-service/config/default?ref=7dd8af7eef873ebca967ba891f34668a7fa9ff58
- integration.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: 7dd8af7eef873ebca967ba891f34668a7fa9ff58

namespace: integration-service

patches:
  - path: ./manager_resources_patch.yaml
